on:
  push:
  workflow_dispatch:
jobs:
  terrascan_job:
    runs-on: ubuntu-latest
    name: terrascan-action
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Terrascan
        id: terrascan
        uses: docker://nasirrabbani/terrascan-action:test3
        with:
          only_warn: true
          verbose: true
          notification_webhook_url: https://6266-103-83-214-125.ngrok.io/v1/api/terrascan
          notification_webhook_token: 64b5d08a-119e-4979-b360-478612190774
          repo_url: https://github.com/pankaj-ora/friendly-journey.git